"""Auto-generate a trainfiles YAML from a natural-language scene description.

The script asks an LLM (Qwen via DashScope's OpenAI-compatible endpoint by
default) to decompose the description into the four scene-level fields
expected by ``trainfiles/*.yaml`` (``text`` / ``part_texts`` /
``part_centers`` / ``part_scales``), then appends the camera and rendering
defaults shared across the bundled examples.

Example::

    export DASHSCOPE_API_KEY=sk-xxxxx
    python llm/llm_gen.py \\
        --description "A robot is reading a book under a tree" \\
        --output trainfiles/robot_reading.yaml

The system prompt that drives the decomposition lives next to this file at
``llm/system.txt``; edit it to bias the LLM toward different decomposition
styles (e.g. tighter scales, more spatial offset, etc.).
"""

import argparse
import os
import re
import sys
from pathlib import Path

from openai import OpenAI


HERE = Path(__file__).resolve().parent
SYSTEM_PROMPT_PATH = HERE / "system.txt"

DEFAULT_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_MODEL = "qwen-plus"  # alternatives: "qwen-max", "qwen3-max"


# Camera / rendering defaults shared across the bundled trainfiles examples.
# Override these per-config after generation if the scene needs different
# framing (e.g. a smaller scene radius for close-up objects).
SCENE_DEFAULTS_TEMPLATE = """\
parts_blob_radius: {parts_blob_radius}

fp16: true
save_mesh: true

IF: true
sd_version: "2.1"

density_activation: "exp"
radius_range: [3.0, 3.5]
default_radius: 3.2
fovy_range: [19, 21]
default_fovy: 20
theta_range: [45, 105]
phi_range: [-180, 180]
default_polar: 90
default_azimuth: 0
bg_radius: 1.4
density_thresh: 1
blob_density: 5.0
blob_radius: 0.2
"""


# ---------------------------------------------------------------------------
# LLM call & parsing
# ---------------------------------------------------------------------------

def call_llm(description: str, *, api_key: str,
             base_url: str = DEFAULT_BASE_URL,
             model: str = DEFAULT_MODEL) -> str:
    """Call the LLM with our system prompt and return the raw response."""
    system_prompt = SYSTEM_PROMPT_PATH.read_text(encoding="utf-8")
    client = OpenAI(api_key=api_key, base_url=base_url)
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": description},
        ],
    )
    return completion.choices[0].message.content


def parse_llm_output(raw: str) -> dict:
    """Extract the four scene fields from the LLM output (line-oriented)."""
    fields = {}
    for line in raw.splitlines():
        stripped = line.strip()
        for key in ("text", "part_texts", "part_centers", "part_scales"):
            prefix = f"{key}:"
            if stripped.startswith(prefix):
                fields[key] = stripped[len(prefix):].strip()
                break

    missing = [k for k in ("text", "part_texts", "part_centers", "part_scales")
               if k not in fields]
    if missing:
        raise ValueError(
            f"Failed to parse LLM output (missing keys {missing}):\n{raw}"
        )

    # Strip any wrapping quotes around the string fields and validate counts.
    for key in ("text", "part_texts"):
        value = fields[key]
        if (value.startswith('"') and value.endswith('"')) \
                or (value.startswith("'") and value.endswith("'")):
            fields[key] = value[1:-1]

    num_parts = fields["part_texts"].count(";") + 1
    num_centers = len(re.findall(r'\[[^\[\]]+\]', fields["part_centers"]))
    if num_centers != num_parts:
        raise ValueError(
            f"Mismatch between part_texts ({num_parts}) and part_centers "
            f"({num_centers}). Raw output:\n{raw}"
        )
    fields["num_parts"] = num_parts
    return fields


# ---------------------------------------------------------------------------
# YAML composition
# ---------------------------------------------------------------------------

def compose_yaml(description: str, fields: dict) -> str:
    """Combine the LLM-decomposed fields with the shared scene defaults."""
    parts_blob_radius = "[" + ", ".join(["0.1"] * fields["num_parts"]) + "]"
    defaults = SCENE_DEFAULTS_TEMPLATE.format(parts_blob_radius=parts_blob_radius)

    return (
        f"# Auto-generated by llm/llm_gen.py from the description:\n"
        f'#   "{description}"\n'
        f"# Review and tweak part_centers / part_scales before training.\n\n"
        f'text: "{fields["text"]}"\n'
        f'part_texts: "{fields["part_texts"]}"\n'
        f"part_centers: {fields['part_centers']}\n"
        f"part_scales: {fields['part_scales']}\n"
        f"\n{defaults}"
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a trainfiles YAML from a scene description via an LLM.",
    )
    parser.add_argument("--description", required=True,
                        help="Natural-language description of the scene to generate.")
    parser.add_argument("--output", required=True,
                        help="Where to write the YAML, e.g. trainfiles/my_scene.yaml.")
    parser.add_argument(
        "--api-key", default=os.environ.get("DASHSCOPE_API_KEY") or os.environ.get("api"),
        help="API key. Defaults to the DASHSCOPE_API_KEY (or 'api') environment variable.",
    )
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL,
                        help=f"OpenAI-compatible endpoint (default: {DEFAULT_BASE_URL}).")
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help=f"Model name (default: {DEFAULT_MODEL}).")
    parser.add_argument("--print-raw", action="store_true",
                        help="Print the raw LLM response in addition to writing the YAML.")
    return parser


def main():
    args = build_arg_parser().parse_args()
    if not args.api_key:
        sys.exit("Error: pass --api-key or set the DASHSCOPE_API_KEY env var.")

    raw = call_llm(
        args.description, api_key=args.api_key,
        base_url=args.base_url, model=args.model,
    )
    if args.print_raw:
        print("=== Raw LLM response ===")
        print(raw)
        print("=" * 24)

    fields = parse_llm_output(raw)
    yaml_text = compose_yaml(args.description, fields)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml_text, encoding="utf-8")
    print(f"Wrote {out_path} ({fields['num_parts']} subspaces).")


if __name__ == "__main__":
    main()
